[[redirects]]
  from = "/es/*"
  to = "/es/index.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/es/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "22.16.0"
