[[redirects]]
  from = "/es/*"
  to = "/es/index.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en-us/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/es/index.html"
  status = 200
